### ISSUE TITLE
Symlinks rotos

### ISSUE THREAD

**Issue by arkhan** [fabianalexisinostroza/El-General#10]
Un saludo, una duda veo que algunos enlaces apuntan a iconos de Breeze, pero la mayoría están rotos, es decir que están apuntando a un icono que no existe, por ejemplo:
```
zoom-select.svg -> /usr/share/icons/breeze/actions/toolbar/zoom-fit-best.svg
```
Y en la ultima versión de Breeze, ese icono esta en la ruta:
```
/usr/share/icons/breeze/actions/24/zoom-fit-best.svg
```

Si me dices como, te puedo ayudar con los enlaces rotos

**Comment by fabianalexisinostroza** [comment]
corregidos, gracias por avisar ;)
