### ISSUE TITLE
Permissions errors

### ISSUE THREAD

**Issue by bertilxi** [fabianalexisinostroza/El-General#11]
The music folder and some mimetypes icons were not displayed, then i tried to change the permissions to 755 and apparently it worked.
I do not know how this has to be but i think that maybe there some mistake with this thing

**Comment by FadeMind** [comment]
Run as root: 

   find /usr/share/icons -type f -exec chmod 644 {} \;
   find /usr/share/icons -type d -exec chmod 755 {} \;

**Comment by fabianalexisinostroza** [comment]
Los permisos están correctos en el tema, puede ser problema de tu sistema, pero ya te dieron solución
