### ISSUE TITLE
El archivo no contiene de tema de iconos válido.

### ISSUE THREAD

**Issue by moshpirit** [fabianalexisinostroza/El-General#12]
Cuando descargo el paquete de iconos (tanto en .zip como en .tar.gz) y lo intento instalar, me devuelve este error:
![instantanea1](https://cloud.githubusercontent.com/assets/7888062/10652130/378b1ec0-7854-11e5-92ff-9d1ae0537c11.png)

**Comment by feskyde** [comment]
Tal parece que es un problema con las configuraciones de KDE, prueba con mover la carpeta 'ElGeneral' a /usr/share/icons

**Comment by fabianalexisinostroza** [comment]
Como dicen arriba, la forma de instalación por medio de las preferencias del sistema de KDE te va a arrojar error, solo funciona (como dice el readme del repositorio) llevando la carpeta a /usr/share/icons . **Esa es la única forma válida de instalación**

**Comment by moshpirit** [comment]
Cierto, ¡gracias!
