### ISSUE TITLE
Otro mimetype

### ISSUE THREAD

**Issue by elav** [fabianalexisinostroza/El-General#13]
Hola, encontré otro mimetype que no está soportado en El General:

.pem

En este caso creo que es una extensión para Chrome: 

uBlock0.chromium.pem

Actualizo: Otro más

MumbleAutomaticCertificateBackup.p12

**Comment by fabianalexisinostroza** [comment]
Muchísimas gracias por el aviso, acabo de agragarlos, van para la versión 1.3 del tema. Así se verán (ya que estos tipos de archivos tienen relación con los certificados) http://i.imgur.com/p1FdmwW.png

**Comment by elav** [comment]
Se ven excelentes :D

**Comment by fabianalexisinostroza** [comment]
gracias :D
