### ISSUE TITLE
In dark theme

### ISSUE THREAD

**Issue by arkhan** [fabianalexisinostroza/El-General#17]
Un saludo se que vas muy ocupado, y que estas haciendo lo posible por sacar el siguiente release, cuando uso este tema con decoraciones oscuras no se ve muy bien, lo que digo se lo puede apreciar en la siguiente captura de dolphin:

![Imgur](http://i.imgur.com/O7ro6eu.png)

**Comment by fabianalexisinostroza** [comment]
está pensado para la v1.3 una variante oscura
