### ISSUE TITLE
Iconos monocromáticos en Kickoff

### ISSUE THREAD

**Issue by elav** [fabianalexisinostroza/El-General#19]
Hola:

Yo de nuevo. Uso un tema oscuro con Plasma y me acabo de dar cuenta, que en el Menú de KDE, los iconos de la categoría Internet, System y Lost & Found son monocromáticos, y no quedan bien sobre el color negro.

**Comment by fabianalexisinostroza** [comment]
eso mismo me di cuenta, así que solucioné el problema, descarga nuevamente el repositorio y me cuentas
