### ISSUE TITLE
Icon request - [Darktable]

### ISSUE THREAD

**Issue by ParanoidNemo** [fabianalexisinostroza/El-General#22]
Well, most of it, I would really like a themed icon for darktable :D If you could and it's fine for you.
Keep up the good work!

**Comment by fabianalexisinostroza** [comment]
i upload an icon in a couple of hours ;)

**Comment by fabianalexisinostroza** [comment]
here is the icon for darktable http://i.imgur.com/ZEOJjr9.png

**Comment by fabianalexisinostroza** [comment]
Finally i added two variants for dark and normal version

![icons 14](https://cloud.githubusercontent.com/assets/14989730/11735037/7f7b772a-9f9b-11e5-8a31-b19954f01918.png)
