### ISSUE TITLE
Sass y Less

### ISSUE THREAD

**Issue by barcia** [fabianalexisinostroza/El-General#23]
Hola, aunque este tema ya cuenta con mimetype para los archivos .css, la realidad es que los que nos dedicamos asl diseño web vivimos todo el tiempo entre archivos de preprocesadores css, como son .sass, .scss o .less, estaría muy bien contar con mimetypes para -al menos- estos tres tipos de archivos.

Intenté brevemente hacerlos yo mismo, simplemente copiando el mimetype del .css y cambiando los colores por los colores oficiales de cada preprocesador (Sass - rosa, Less - azul) pero la verdad es que no soy muy diestro con dibujos vectoriales.

**Comment by fabianalexisinostroza** [comment]
Se pueden agregar sin problemas, pero recuerda que más allá del mimetype, depende como lo reconoce Plasma, por eso te pido si es que puedes darme la asociación del archivo, por ejemplo:

text-x-nombredeextensión

**Comment by fabianalexisinostroza** [comment]
Ya los tengo creados, los acabo de subir al repositorio github, te adjunto como son los mimetypes 
![icons 16](https://cloud.githubusercontent.com/assets/14989730/11748538/88383d00-a007-11e5-8e60-2f38c8f1e4fa.png)

![icons 17](https://cloud.githubusercontent.com/assets/14989730/11748565/a6390e24-a007-11e5-8d25-309760cd52fa.png)

Ahora para poder usarlos debes entrar en las preferencias de Plasma, en Alicaciones/asosiación de archivos para lo cual debes colocar lo siguiente.

Para *.sass
![icons 18](https://cloud.githubusercontent.com/assets/14989730/11748593/c4202936-a007-11e5-880e-a12f28800438.png)

Para *.scss
![icons 19](https://cloud.githubusercontent.com/assets/14989730/11748596/c9dbd708-a007-11e5-9371-5ec1b715a8ea.png)

Para *.less
![icons 20](https://cloud.githubusercontent.com/assets/14989730/11748607/d569e93e-a007-11e5-85ce-03a56e7f24a2.png)

**Comment by fabianalexisinostroza** [comment]
acabo de subir una revisión del *.less que tenía un tamaño de letra un poco grande

**Comment by barcia** [comment]
Perfecto! muchas gracias!

**Comment by fabianalexisinostroza** [comment]
no hay de que (:
