### ISSUE TITLE
Spectacle

### ISSUE THREAD

**Issue by barcia** [fabianalexisinostroza/El-General#25]
Ayer (16 de diciembre) se liberó KDE Applications 15.12.0 con la novedad de que se reemplazó la aplicación _**KSnapshot**_ por una completamente nueva llamada _**Spectacle**_. La función es la misma, y el icono muy parecido, así que te podría servir el mismo icono usado para _KSnapshot_, simplemente debes cambiar el nombre del viejo `ksnapshot.svg` por `spectacle.svg`.

**Comment by fabianalexisinostroza** [comment]
gracias por el aviso, yo sigo en plasma 5.4 y en las KDE Applications anterior, así que lo que haré será usar el mismo icono de ksnapshot para spectable
