### ISSUE TITLE
icono CDDB extra grande

### ISSUE THREAD

**Issue by arkhan** [fabianalexisinostroza/El-General#28]
Un saludo, haces un gran trabajo con este tema, actualmente uso ArchLinux + Plasma + AwesomeWM, algunas veces tengo que usar aplicaciones GTK, se que este pack esta orientado exclusivamente a Plasma, el icono de CDDB en easytag se visualiza mal como se puede ver en la captura

![Imgur](http://i.imgur.com/9OT5Cj8.png)

**Comment by fabianalexisinostroza** [comment]
es raro, porque el ícono simbólico (media optical) se encuentra en el set, debe ser un problema de la aplicación. Además para comprobarlo, bajé la aplicación en Chakra y no se ve como en tu caso.

![screenshot_20160103_154013](https://cloud.githubusercontent.com/assets/14989730/12080138/4bffc73c-b230-11e5-9596-fa8cc39533ab.png)

**Comment by arkhan** [comment]
Creo que es por la versión de easytag

**Comment by feskyde** [comment]
Ese es un bug conocido de GTK3, los iconos .svg tienden a mostrarse más grandes de lo que son (a 18 versiones estables todavia no se arregló, parece)

**Comment by feskyde** [comment]
Y como dice @arkhan es posible que la version de EasyTag que está usando @fabianalexisinostroza es la GTK2 :grin:

**Comment by fabianalexisinostroza** [comment]
debe ser lo más probable :+1:
