### ISSUE TITLE
Iconos Kmail

### ISSUE THREAD

**Issue by barcia** [fabianalexisinostroza/El-General#29]
He detectado dos pequeños bugs con la aplicación de Kmail, el primero, es simplemente que el icono de Kmail (kmail.svg) es un icono que no corresponde (adjunto una captura), y creo que el icono que debería ser, está nombrado como kmail2.svg.
![screenshot_20160122_013549](https://cloud.githubusercontent.com/assets/5719646/12499210/cfdeb5a0-c0a8-11e5-9a38-ac2062996fa8.png)

Otro pequeño fallo es con el icono de la bandeja de notificaciones (aunque creo que este puede ser fallo directamente del pack de iconos Breeze, y no de El General), cuando no hay mensajes se muestra ccorrectamente, pero cuando hay mensajes muestra un icono como más "feo" o "antiguo".
![screenshot_20160122_012123](https://cloud.githubusercontent.com/assets/5719646/12499252/39051538-c0a9-11e5-8eb6-62c022b001a3.png)

**Comment by fabianalexisinostroza** [comment]
el icono de kmail, el de kmail 2 es otro, son diferentes, no hay problema con eso. Lo de la notificación es el tema plasma
