### ISSUE TITLE
Excelente

### ISSUE THREAD

**Issue by vmorenomarin** [fabianalexisinostroza/El-General#4]
Hombre está muy completo y bonito. Sería genial un repositorio donde tuviéramos la oportunidad de mantenerlos actualizados.

**Comment by fabianalexisinostroza** [comment]
te refieres a algo tipo PPA en ubuntu?. Pues yo no se empaquetar, sino hubiera sido excelente para mantener actualizados sin hacer muchos pasos. Igual insto a alguien que quiera ayudarme a empaquetar y crear un repositorio de ese tipo, bienvenido sea, sobretodo porque yo actualizaré a ritmo semanal.

**Comment by vmorenomarin** [comment]
Comprendo. Bueno, siendo así, estaré al tanto de las actualizaciones que mantengas por acá. Supongo que las informarás en tu blog, el cual agregué a mis feeds. Está muy bueno el tema, muy buen aspecto le da a Plasma 5, felicitaciones.

**Comment by fabianalexisinostroza** [comment]
Gracias, y si, cada nueva versión detallaré los cambios en mi blog ;)

**Comment by technox64** [comment]
muy buen pack de iconos, te queria pedir permiso si puedo crear un package de el, para el repo de aur en archlinux y mantenerlo actualizado

**Comment by fabianalexisinostroza** [comment]
no hay ningún problema, todo lo contrario, tienes permiso y como digo anteriormente, los iconos se actualizarán semanalmente
