### ISSUE TITLE
Google Apps

### ISSUE THREAD

**Issue by barcia** [fabianalexisinostroza/El-General#5]
Gracias por este estupendo tema!! se ve genial en mi  Manjaro.

Sería genial contar con los iconos de las Google Apps (creo que Play Music ya está, pero a mi no me aparece)

También estaría genial el icono de PopcornTime

![captura2](https://cloud.githubusercontent.com/assets/5719646/10465442/34578b78-71ef-11e5-8a40-b518abff9874.png)

**Comment by fabianalexisinostroza** [comment]
Gracias a ti por descargarlo, el icono de google play music está por ese nombre en apps, Intentaré agregarlos en la actualización semanal. Si no me equivoco, estas apps de chrome son editables desde el editor de menu de KDE así que en el tema lo más probable es que estén con su nombre "normal".  Te invito para el día domingo revisar los cambios (ya que los domingos son las actualizaciones del tema).

En relación a manjaro, me permitiré comentar que se viene algo especial. Saludos

**Comment by fabianalexisinostroza** [comment]
agregados para la versión 1.2 así que cerraré este issue
