### ISSUE TITLE
Iconos faltantes

### ISSUE THREAD

**Issue by elav** [fabianalexisinostroza/El-General#6]
Hey Fabian, tremendo trabajo. Estuve revisando y hay algunos iconos (Mimetypes) que faltan. Son los relacionados con:

- .apk (App de Android)
- .xpi (Extensión de Firefox)
- .sql (Fichero de BD de MySQL)
- .msi (Instalador de Windows)
- .ini (Fichero de Windows)
- .p12 (Fichero de OpenVPN)

Si encuentro algún otro te lo dejo saber..

**Comment by fabianalexisinostroza** [comment]
el .apk se encuentra, lo más probable es que el tema breeze tenga otro nombre relacionado a él, puede ser eso.

**Comment by fabianalexisinostroza** [comment]
igual me sería de ayuda, de bastante ayuda, los nombres que deberían tener las extensiones de archivo para su correcta asociación

**Comment by elav** [comment]
Bueno, si encuentro algo más te aviso sin problema.. :D

**Comment by fabianalexisinostroza** [comment]
solo me faltaron el .p12 y el .ini (aunque ese es reconocido como archivo de texto)
