### ISSUE TITLE
icons request.

### ISSUE THREAD

**Issue by arkhan** [fabianalexisinostroza/El-General#7]
Un saludo gran trabajo, puedes agregar los siguientes iconos:
Aplicaciones:
- Terminator
- web
- help
- package_settings
- web-browser
- Keepassx
- Keepass
- Kvantum Manager
- SpaceFM
- Geany
- git-cola
- git-dag
- GNU Emacs
- Kompare
- Meld
- Mumble
- easyMP3Gain
- Kamerka
- mpv
- soundKonverter
- MKVToolNix GUI
- qTox
- Kile
- Texmaker
- Texstudio
- Thunderbird
- Trojita
- VirtualBox

MineTypes
*.mo
*.po 
*.xpi
*.js
*.kdbx
*.asc

**Comment by fabianalexisinostroza** [comment]
gracias por comentar, hay algunos que mencionas que si se encuentran, te invito a revisar losr archivos del tema

**Comment by fabianalexisinostroza** [comment]
las extensiones, en lo posible necesito que me detallen el nombre que debería tener para poder coincidir con el tema

**Comment by arkhan** [comment]
*.mo (application/x-gettext-translation)
*.po (text/x-gettext-translation)
*.xpi (application/x-xpinstall)
*.js (application/javascript)
*.kdbx (application/x-keepass2)
*.asc (application/pgp-encrypted)

**Comment by fabianalexisinostroza** [comment]
me refería a que nombre debería tener no se por ejemplo .... "text-x-mo.svg"

**Comment by arkhan** [comment]
Esa es el tipo de archivo por cada extensión application-x-keepass2.svg en el caso de los archivos de keepass2

**Comment by vmorenomarin** [comment]
Uy, qué bien la de Kile. Breeze tampoco lo tiene.

**Comment by arkhan** [comment]
Podrías reconsiderar cambiar el nombre de la carpeta contenedora del tema de iconos, ya que algunas aplicaciones no reconocen el nombre "El General", como en la siguiente linea:
 ```
urxvt: "General/apps/software/utilities-terminal.svg": malformed option.
```
AwesomeWM no reconoce el tema debido al espacio en el nombre de la carpeta
Gracias por la atención..

**Comment by fabianalexisinostroza** [comment]
Cambiar el nombre me implicaría demasiado trabajo reacomodando algunos enlaces y otros archivos, de momento lo veo poco posible. Pero eres libre de forkear el tema y hacerle las modificaciones que quieras

**Comment by arkhan** [comment]
ok

**Comment by CrisBRM** [comment]
An icon for skype would be most welcome as well.

**Comment by arkhan** [comment]
Update:
Faltan minetypes para
*.ass (text/x-ssa)
*.srt (application/x-subrip)

**Comment by fabianalexisinostroza** [comment]
agregados *.ass y *.srt http://i.imgur.com/b8TuoIj.png también el *.kdbx

**Comment by al-dy** [comment]
Hola, unos iconos que no están en Breeze:

- Subtitle Composer (subtitlecomposer) => Editor de subtítulos de KDE.
- Synfig Studio (synfigstudio) => Programa de animación.
- *.sif (application/x-sif) => MineTypes para los archivos de Synfig. (Dolphin no muestra ningún icono para estos archivos)

El no estar los iconos del MineType para los archivos *.sif

**Comment by CrisBRM** [comment]
Docky's icon should be mandatory! Just kidding. Keep up the good work and merry christmas!

**Comment by fabianalexisinostroza** [comment]
hahaha merry christmas !

**Comment by fabianalexisinostroza** [comment]
todos los iconos acaban de ser añadidos, ya se encuentran en el repositorio. Por fin después de largo tiempo desde este issue, se cerrará (:
