### ISSUE TITLE
Usa la seccion "releases" para cada lanzamiento

### ISSUE THREAD

**Issue by feskyde** [fabianalexisinostroza/El-General#8]
Hola Fabián

Estoy tratando de crear un PKGBUILD para Arch/Manjaro para tu tema de iconos, del ultimo lanzamiento pero no existe el link, ya que no usas la seccion "releases".

Yendo al grano, ¿podrias hacer un tag nuevo así yo puedo subir el PKGBUILD?

**Comment by fabianalexisinostroza** [comment]
ya había una persona que estaba creando un paquete para Arch

**Comment by feskyde** [comment]
Ah, bueno, me ahorro el trabajo entonces :grin:

**Comment by fabianalexisinostroza** [comment]
jajaja lo mejor es ahorrarse trabajo :D

**Comment by feskyde** [comment]
Cierto :smile:

PD: Por si pasa algo, voy a dejar mi PKGBUILD [acá](https://github.com/feskyde/PKGBUILDs).

**Comment by feskyde** [comment]
Aunque igual deberías tener en cuenta mi recomendacion, usa la seccion "releases" cuando hagas un nuevo lanzamiento

**Comment by fabianalexisinostroza** [comment]
Seguí tu consejo ;)

**Comment by feskyde** [comment]
Sobre los PKGBUILD (para `v1.2` y `master`), ya los mandé al CCR de Chakra :grin:

**Comment by fabianalexisinostroza** [comment]
excelente :D muy agradecido
